kind: perf
args:
  batch_size: null
  warmup: 1
  log_base: logs
  alpha: 0.0
  beta: 0.0
  iterations: 100
  min_iterations: 3
  qps_relative_ci_half_width: 0.05
  exp_name: 2IVF
  step_nprobe: 40
  per_dataset:
    laion_all:
      high_nprobe: 2048
    laion_pos:
      high_nprobe: 1024
    laion_neg:
      high_nprobe: 2048
    yfcc:
      high_nprobe: 4096
    yfcc_single:
      high_nprobe: 4096
    sift_r10:
      low_nprobe: 24
      high_nprobe: 768
    sift_r20:
      low_nprobe: 16
      high_nprobe: 768
    sift_r40:
      low_nprobe: 16
      high_nprobe: 768
